### PR TITLE
Setup Action for Xamarin App

### PR DESCRIPTION
**Pull request by Thomas-Julien-SAHUT**

### CODE REVIEW

**Comment by nicolas63** [comment]
@Thomas-Julien-SAHUT the ci work now, can you merge it and open a new PR to run UT during ci ?

**Comment by Thomas-Julien-SAHUT** [comment]
I can't merge this, a review is required .

**Review by nicolas63 — APPROVED** [review]

**Comment by nicolas63** [comment]
Done

**Comment by Thomas-Julien-SAHUT** [comment]
The new PR have to compare the Xamarin-App-Action's branch and UT's branch ?

**Comment by nicolas63** [comment]
No it's to run UT with ci

**Pull request merged**
